#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nephrite.CMS.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Fund2")]
	public partial class modelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSiteItem(SiteItem instance);
    partial void UpdateSiteItem(SiteItem instance);
    partial void DeleteSiteItem(SiteItem instance);
    partial void InsertSiteItemsFolder(SiteItemsFolder instance);
    partial void UpdateSiteItemsFolder(SiteItemsFolder instance);
    partial void DeleteSiteItemsFolder(SiteItemsFolder instance);
    partial void InsertMM_ObjectType(MM_ObjectType instance);
    partial void UpdateMM_ObjectType(MM_ObjectType instance);
    partial void DeleteMM_ObjectType(MM_ObjectType instance);
    partial void InsertMM_ObjectProperty(MM_ObjectProperty instance);
    partial void UpdateMM_ObjectProperty(MM_ObjectProperty instance);
    partial void DeleteMM_ObjectProperty(MM_ObjectProperty instance);
    partial void InsertSiteInfoobject(SiteInfoobject instance);
    partial void UpdateSiteInfoobject(SiteInfoobject instance);
    partial void DeleteSiteInfoobject(SiteInfoobject instance);
    partial void InsertSiteSection(SiteSection instance);
    partial void UpdateSiteSection(SiteSection instance);
    partial void DeleteSiteSection(SiteSection instance);
    partial void InsertSiteObject(SiteObject instance);
    partial void UpdateSiteObject(SiteObject instance);
    partial void DeleteSiteObject(SiteObject instance);
    #endregion
		
		public modelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public modelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public modelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public modelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public modelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SiteItem> SiteItems
		{
			get
			{
				return this.GetTable<SiteItem>();
			}
		}
		
		public System.Data.Linq.Table<SiteItemsFolder> SiteItemsFolders
		{
			get
			{
				return this.GetTable<SiteItemsFolder>();
			}
		}
		
		public System.Data.Linq.Table<MM_ObjectType> MM_ObjectTypes
		{
			get
			{
				return this.GetTable<MM_ObjectType>();
			}
		}
		
		public System.Data.Linq.Table<MM_ObjectProperty> MM_ObjectProperties
		{
			get
			{
				return this.GetTable<MM_ObjectProperty>();
			}
		}
		
		public System.Data.Linq.Table<SiteInfoobject> SiteInfoobjects
		{
			get
			{
				return this.GetTable<SiteInfoobject>();
			}
		}
		
		public System.Data.Linq.Table<SiteSection> SiteSections
		{
			get
			{
				return this.GetTable<SiteSection>();
			}
		}
		
		public System.Data.Linq.Table<SiteObject> SiteObjects
		{
			get
			{
				return this.GetTable<SiteObject>();
			}
		}
		
		public System.Data.Linq.Table<V_SiteObject> V_SiteObjects
		{
			get
			{
				return this.GetTable<V_SiteObject>();
			}
		}
		
		public System.Data.Linq.Table<V_SiteSection> V_SiteSections
		{
			get
			{
				return this.GetTable<V_SiteSection>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SiteItem")]
	public partial class SiteItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SiteItemID;
		
		private bool _IsDeleted;
		
		private System.DateTime _LastModifiedDate;
		
		private int _LastModifiedUserID;
		
		private string _Title;
		
		private int _ParentID;
		
		private string _Content;
		
		private string _SysName;
		
		private EntityRef<SiteItemsFolder> _SiteItemsFolder;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSiteItemIDChanging(int value);
    partial void OnSiteItemIDChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnLastModifiedDateChanging(System.DateTime value);
    partial void OnLastModifiedDateChanged();
    partial void OnLastModifiedUserIDChanging(int value);
    partial void OnLastModifiedUserIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnParentIDChanging(int value);
    partial void OnParentIDChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnSysNameChanging(string value);
    partial void OnSysNameChanged();
    #endregion
		
		public SiteItem()
		{
			this._SiteItemsFolder = default(EntityRef<SiteItemsFolder>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteItemID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SiteItemID
		{
			get
			{
				return this._SiteItemID;
			}
			set
			{
				if ((this._SiteItemID != value))
				{
					this.OnSiteItemIDChanging(value);
					this.SendPropertyChanging();
					this._SiteItemID = value;
					this.SendPropertyChanged("SiteItemID");
					this.OnSiteItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastModifiedDate
		{
			get
			{
				return this._LastModifiedDate;
			}
			set
			{
				if ((this._LastModifiedDate != value))
				{
					this.OnLastModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedDate = value;
					this.SendPropertyChanged("LastModifiedDate");
					this.OnLastModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedUserID", DbType="Int NOT NULL")]
		public int LastModifiedUserID
		{
			get
			{
				return this._LastModifiedUserID;
			}
			set
			{
				if ((this._LastModifiedUserID != value))
				{
					this.OnLastModifiedUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedUserID = value;
					this.SendPropertyChanged("LastModifiedUserID");
					this.OnLastModifiedUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int NOT NULL")]
		public int ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					if (this._SiteItemsFolder.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnParentIDChanging(value);
					this.SendPropertyChanging();
					this._ParentID = value;
					this.SendPropertyChanged("ParentID");
					this.OnParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string SysName
		{
			get
			{
				return this._SysName;
			}
			set
			{
				if ((this._SysName != value))
				{
					this.OnSysNameChanging(value);
					this.SendPropertyChanging();
					this._SysName = value;
					this.SendPropertyChanged("SysName");
					this.OnSysNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SiteItemsFolder_SiteItem", Storage="_SiteItemsFolder", ThisKey="ParentID", OtherKey="SiteItemsFolderID", IsForeignKey=true)]
		public SiteItemsFolder SiteItemsFolder
		{
			get
			{
				return this._SiteItemsFolder.Entity;
			}
			set
			{
				SiteItemsFolder previousValue = this._SiteItemsFolder.Entity;
				if (((previousValue != value) 
							|| (this._SiteItemsFolder.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SiteItemsFolder.Entity = null;
						previousValue.SiteItems.Remove(this);
					}
					this._SiteItemsFolder.Entity = value;
					if ((value != null))
					{
						value.SiteItems.Add(this);
						this._ParentID = value.SiteItemsFolderID;
					}
					else
					{
						this._ParentID = default(int);
					}
					this.SendPropertyChanged("SiteItemsFolder");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SiteItemsFolder")]
	public partial class SiteItemsFolder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SiteItemsFolderID;
		
		private bool _IsDeleted;
		
		private System.DateTime _LastModifiedDate;
		
		private int _LastModifiedUserID;
		
		private string _Title;
		
		private EntitySet<SiteItem> _SiteItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSiteItemsFolderIDChanging(int value);
    partial void OnSiteItemsFolderIDChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnLastModifiedDateChanging(System.DateTime value);
    partial void OnLastModifiedDateChanged();
    partial void OnLastModifiedUserIDChanging(int value);
    partial void OnLastModifiedUserIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    #endregion
		
		public SiteItemsFolder()
		{
			this._SiteItems = new EntitySet<SiteItem>(new Action<SiteItem>(this.attach_SiteItems), new Action<SiteItem>(this.detach_SiteItems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteItemsFolderID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SiteItemsFolderID
		{
			get
			{
				return this._SiteItemsFolderID;
			}
			set
			{
				if ((this._SiteItemsFolderID != value))
				{
					this.OnSiteItemsFolderIDChanging(value);
					this.SendPropertyChanging();
					this._SiteItemsFolderID = value;
					this.SendPropertyChanged("SiteItemsFolderID");
					this.OnSiteItemsFolderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastModifiedDate
		{
			get
			{
				return this._LastModifiedDate;
			}
			set
			{
				if ((this._LastModifiedDate != value))
				{
					this.OnLastModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedDate = value;
					this.SendPropertyChanged("LastModifiedDate");
					this.OnLastModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedUserID", DbType="Int NOT NULL")]
		public int LastModifiedUserID
		{
			get
			{
				return this._LastModifiedUserID;
			}
			set
			{
				if ((this._LastModifiedUserID != value))
				{
					this.OnLastModifiedUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedUserID = value;
					this.SendPropertyChanged("LastModifiedUserID");
					this.OnLastModifiedUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SiteItemsFolder_SiteItem", Storage="_SiteItems", ThisKey="SiteItemsFolderID", OtherKey="ParentID")]
		public EntitySet<SiteItem> SiteItems
		{
			get
			{
				return this._SiteItems;
			}
			set
			{
				this._SiteItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SiteItems(SiteItem entity)
		{
			this.SendPropertyChanging();
			entity.SiteItemsFolder = this;
		}
		
		private void detach_SiteItems(SiteItem entity)
		{
			this.SendPropertyChanging();
			entity.SiteItemsFolder = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MM_ObjectType")]
	public partial class MM_ObjectType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ObjectTypeID;
		
		private string _Title;
		
		private string _SysName;
		
		private bool _IsEnableSPM;
		
		private int _PackageID;
		
		private System.Guid _Guid;
		
		private bool _IsSeparateTable;
		
		private bool _IsTemplate;
		
		private string _TitlePlural;
		
		private System.Nullable<int> _BaseObjectTypeID;
		
		private string _DefaultOrderBy;
		
		private string _IsLogicalDelete;
		
		private bool _IsReplicate;
		
		private bool _IsEnableUserViews;
		
		private string _SecurityPackageSystemName;
		
		private bool _IsEnableObjectHistory;
		
		private string _Interface;
		
		private string _HistoryTypeCode;
		
		private bool _IsDataReplicated;
		
		private EntitySet<MM_ObjectType> _MM_ObjectTypes;
		
		private EntitySet<MM_ObjectProperty> _MM_ObjectProperties;
		
		private EntitySet<MM_ObjectProperty> _MM_ObjectProperties1;
		
		private EntityRef<SiteInfoobject> _SiteInfoobject;
		
		private EntityRef<MM_ObjectType> _MM_ObjectType1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnObjectTypeIDChanging(int value);
    partial void OnObjectTypeIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnSysNameChanging(string value);
    partial void OnSysNameChanged();
    partial void OnIsEnableSPMChanging(bool value);
    partial void OnIsEnableSPMChanged();
    partial void OnPackageIDChanging(int value);
    partial void OnPackageIDChanged();
    partial void OnGuidChanging(System.Guid value);
    partial void OnGuidChanged();
    partial void OnIsSeparateTableChanging(bool value);
    partial void OnIsSeparateTableChanged();
    partial void OnIsTemplateChanging(bool value);
    partial void OnIsTemplateChanged();
    partial void OnTitlePluralChanging(string value);
    partial void OnTitlePluralChanged();
    partial void OnBaseObjectTypeIDChanging(System.Nullable<int> value);
    partial void OnBaseObjectTypeIDChanged();
    partial void OnDefaultOrderByChanging(string value);
    partial void OnDefaultOrderByChanged();
    partial void OnLogicalDeleteChanging(string value);
    partial void OnLogicalDeleteChanged();
    partial void OnIsReplicateChanging(bool value);
    partial void OnIsReplicateChanged();
    partial void OnIsEnableUserViewsChanging(bool value);
    partial void OnIsEnableUserViewsChanged();
    partial void OnSecurityPackageSystemNameChanging(string value);
    partial void OnSecurityPackageSystemNameChanged();
    partial void OnIsEnableObjectHistoryChanging(bool value);
    partial void OnIsEnableObjectHistoryChanged();
    partial void OnInterfaceChanging(string value);
    partial void OnInterfaceChanged();
    partial void OnHistoryTypeCodeChanging(string value);
    partial void OnHistoryTypeCodeChanged();
    partial void OnIsDataReplicatedChanging(bool value);
    partial void OnIsDataReplicatedChanged();
    #endregion
		
		public MM_ObjectType()
		{
			this._MM_ObjectTypes = new EntitySet<MM_ObjectType>(new Action<MM_ObjectType>(this.attach_MM_ObjectTypes), new Action<MM_ObjectType>(this.detach_MM_ObjectTypes));
			this._MM_ObjectProperties = new EntitySet<MM_ObjectProperty>(new Action<MM_ObjectProperty>(this.attach_MM_ObjectProperties), new Action<MM_ObjectProperty>(this.detach_MM_ObjectProperties));
			this._MM_ObjectProperties1 = new EntitySet<MM_ObjectProperty>(new Action<MM_ObjectProperty>(this.attach_MM_ObjectProperties1), new Action<MM_ObjectProperty>(this.detach_MM_ObjectProperties1));
			this._SiteInfoobject = default(EntityRef<SiteInfoobject>);
			this._MM_ObjectType1 = default(EntityRef<MM_ObjectType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectTypeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ObjectTypeID
		{
			get
			{
				return this._ObjectTypeID;
			}
			set
			{
				if ((this._ObjectTypeID != value))
				{
					this.OnObjectTypeIDChanging(value);
					this.SendPropertyChanging();
					this._ObjectTypeID = value;
					this.SendPropertyChanged("ObjectTypeID");
					this.OnObjectTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(1024) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string SysName
		{
			get
			{
				return this._SysName;
			}
			set
			{
				if ((this._SysName != value))
				{
					this.OnSysNameChanging(value);
					this.SendPropertyChanging();
					this._SysName = value;
					this.SendPropertyChanged("SysName");
					this.OnSysNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEnableSPM", DbType="Bit NOT NULL")]
		public bool IsEnableSPM
		{
			get
			{
				return this._IsEnableSPM;
			}
			set
			{
				if ((this._IsEnableSPM != value))
				{
					this.OnIsEnableSPMChanging(value);
					this.SendPropertyChanging();
					this._IsEnableSPM = value;
					this.SendPropertyChanged("IsEnableSPM");
					this.OnIsEnableSPMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageID", DbType="Int NOT NULL")]
		public int PackageID
		{
			get
			{
				return this._PackageID;
			}
			set
			{
				if ((this._PackageID != value))
				{
					this.OnPackageIDChanging(value);
					this.SendPropertyChanging();
					this._PackageID = value;
					this.SendPropertyChanged("PackageID");
					this.OnPackageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Guid
		{
			get
			{
				return this._Guid;
			}
			set
			{
				if ((this._Guid != value))
				{
					this.OnGuidChanging(value);
					this.SendPropertyChanging();
					this._Guid = value;
					this.SendPropertyChanged("Guid");
					this.OnGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSeparateTable", DbType="Bit NOT NULL")]
		public bool IsSeparateTable
		{
			get
			{
				return this._IsSeparateTable;
			}
			set
			{
				if ((this._IsSeparateTable != value))
				{
					this.OnIsSeparateTableChanging(value);
					this.SendPropertyChanging();
					this._IsSeparateTable = value;
					this.SendPropertyChanged("IsSeparateTable");
					this.OnIsSeparateTableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsTemplate", DbType="Bit NOT NULL")]
		public bool IsTemplate
		{
			get
			{
				return this._IsTemplate;
			}
			set
			{
				if ((this._IsTemplate != value))
				{
					this.OnIsTemplateChanging(value);
					this.SendPropertyChanging();
					this._IsTemplate = value;
					this.SendPropertyChanged("IsTemplate");
					this.OnIsTemplateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitlePlural", DbType="NVarChar(1024)")]
		public string TitlePlural
		{
			get
			{
				return this._TitlePlural;
			}
			set
			{
				if ((this._TitlePlural != value))
				{
					this.OnTitlePluralChanging(value);
					this.SendPropertyChanging();
					this._TitlePlural = value;
					this.SendPropertyChanged("TitlePlural");
					this.OnTitlePluralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseObjectTypeID", DbType="Int")]
		public System.Nullable<int> BaseObjectTypeID
		{
			get
			{
				return this._BaseObjectTypeID;
			}
			set
			{
				if ((this._BaseObjectTypeID != value))
				{
					if (this._MM_ObjectType1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBaseObjectTypeIDChanging(value);
					this.SendPropertyChanging();
					this._BaseObjectTypeID = value;
					this.SendPropertyChanged("BaseObjectTypeID");
					this.OnBaseObjectTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultOrderBy", DbType="NVarChar(1024)")]
		public string DefaultOrderBy
		{
			get
			{
				return this._DefaultOrderBy;
			}
			set
			{
				if ((this._DefaultOrderBy != value))
				{
					this.OnDefaultOrderByChanging(value);
					this.SendPropertyChanging();
					this._DefaultOrderBy = value;
					this.SendPropertyChanged("DefaultOrderBy");
					this.OnDefaultOrderByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLogicalDelete", DbType="NVarChar(MAX)")]
		public string LogicalDelete
		{
			get
			{
				return this._IsLogicalDelete;
			}
			set
			{
				if ((this._IsLogicalDelete != value))
				{
					this.OnLogicalDeleteChanging(value);
					this.SendPropertyChanging();
					this._IsLogicalDelete = value;
					this.SendPropertyChanged("LogicalDelete");
					this.OnLogicalDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReplicate", DbType="Bit NOT NULL")]
		public bool IsReplicate
		{
			get
			{
				return this._IsReplicate;
			}
			set
			{
				if ((this._IsReplicate != value))
				{
					this.OnIsReplicateChanging(value);
					this.SendPropertyChanging();
					this._IsReplicate = value;
					this.SendPropertyChanged("IsReplicate");
					this.OnIsReplicateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEnableUserViews", DbType="Bit NOT NULL")]
		public bool IsEnableUserViews
		{
			get
			{
				return this._IsEnableUserViews;
			}
			set
			{
				if ((this._IsEnableUserViews != value))
				{
					this.OnIsEnableUserViewsChanging(value);
					this.SendPropertyChanging();
					this._IsEnableUserViews = value;
					this.SendPropertyChanged("IsEnableUserViews");
					this.OnIsEnableUserViewsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityPackageSystemName", DbType="NVarChar(255)")]
		public string SecurityPackageSystemName
		{
			get
			{
				return this._SecurityPackageSystemName;
			}
			set
			{
				if ((this._SecurityPackageSystemName != value))
				{
					this.OnSecurityPackageSystemNameChanging(value);
					this.SendPropertyChanging();
					this._SecurityPackageSystemName = value;
					this.SendPropertyChanged("SecurityPackageSystemName");
					this.OnSecurityPackageSystemNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEnableObjectHistory", DbType="Bit NOT NULL")]
		public bool IsEnableObjectHistory
		{
			get
			{
				return this._IsEnableObjectHistory;
			}
			set
			{
				if ((this._IsEnableObjectHistory != value))
				{
					this.OnIsEnableObjectHistoryChanging(value);
					this.SendPropertyChanging();
					this._IsEnableObjectHistory = value;
					this.SendPropertyChanged("IsEnableObjectHistory");
					this.OnIsEnableObjectHistoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Interface", DbType="NVarChar(1024)")]
		public string Interface
		{
			get
			{
				return this._Interface;
			}
			set
			{
				if ((this._Interface != value))
				{
					this.OnInterfaceChanging(value);
					this.SendPropertyChanging();
					this._Interface = value;
					this.SendPropertyChanged("Interface");
					this.OnInterfaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HistoryTypeCode", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string HistoryTypeCode
		{
			get
			{
				return this._HistoryTypeCode;
			}
			set
			{
				if ((this._HistoryTypeCode != value))
				{
					this.OnHistoryTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HistoryTypeCode = value;
					this.SendPropertyChanged("HistoryTypeCode");
					this.OnHistoryTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDataReplicated", DbType="Bit NOT NULL")]
		public bool IsDataReplicated
		{
			get
			{
				return this._IsDataReplicated;
			}
			set
			{
				if ((this._IsDataReplicated != value))
				{
					this.OnIsDataReplicatedChanging(value);
					this.SendPropertyChanging();
					this._IsDataReplicated = value;
					this.SendPropertyChanged("IsDataReplicated");
					this.OnIsDataReplicatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MM_ObjectType_MM_ObjectType", Storage="_MM_ObjectTypes", ThisKey="ObjectTypeID", OtherKey="BaseObjectTypeID")]
		public EntitySet<MM_ObjectType> MM_ObjectTypes
		{
			get
			{
				return this._MM_ObjectTypes;
			}
			set
			{
				this._MM_ObjectTypes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MM_ObjectType_MM_ObjectProperty", Storage="_MM_ObjectProperties", ThisKey="ObjectTypeID", OtherKey="ObjectTypeID")]
		public EntitySet<MM_ObjectProperty> MM_ObjectProperties
		{
			get
			{
				return this._MM_ObjectProperties;
			}
			set
			{
				this._MM_ObjectProperties.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MM_ObjectType_MM_ObjectProperty1", Storage="_MM_ObjectProperties1", ThisKey="ObjectTypeID", OtherKey="RefObjectTypeID")]
		public EntitySet<MM_ObjectProperty> MM_ObjectProperties1
		{
			get
			{
				return this._MM_ObjectProperties1;
			}
			set
			{
				this._MM_ObjectProperties1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MM_ObjectType_SiteInfoobject", Storage="_SiteInfoobject", ThisKey="ObjectTypeID", OtherKey="SiteInfoobjectsID", IsUnique=true, IsForeignKey=false)]
		public SiteInfoobject SiteInfoobject
		{
			get
			{
				return this._SiteInfoobject.Entity;
			}
			set
			{
				SiteInfoobject previousValue = this._SiteInfoobject.Entity;
				if (((previousValue != value) 
							|| (this._SiteInfoobject.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SiteInfoobject.Entity = null;
						previousValue.MM_ObjectType = null;
					}
					this._SiteInfoobject.Entity = value;
					if ((value != null))
					{
						value.MM_ObjectType = this;
					}
					this.SendPropertyChanged("SiteInfoobject");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MM_ObjectType_MM_ObjectType", Storage="_MM_ObjectType1", ThisKey="BaseObjectTypeID", OtherKey="ObjectTypeID", IsForeignKey=true)]
		public MM_ObjectType MM_ObjectType1
		{
			get
			{
				return this._MM_ObjectType1.Entity;
			}
			set
			{
				MM_ObjectType previousValue = this._MM_ObjectType1.Entity;
				if (((previousValue != value) 
							|| (this._MM_ObjectType1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MM_ObjectType1.Entity = null;
						previousValue.MM_ObjectTypes.Remove(this);
					}
					this._MM_ObjectType1.Entity = value;
					if ((value != null))
					{
						value.MM_ObjectTypes.Add(this);
						this._BaseObjectTypeID = value.ObjectTypeID;
					}
					else
					{
						this._BaseObjectTypeID = default(Nullable<int>);
					}
					this.SendPropertyChanged("MM_ObjectType1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MM_ObjectTypes(MM_ObjectType entity)
		{
			this.SendPropertyChanging();
			entity.MM_ObjectType1 = this;
		}
		
		private void detach_MM_ObjectTypes(MM_ObjectType entity)
		{
			this.SendPropertyChanging();
			entity.MM_ObjectType1 = null;
		}
		
		private void attach_MM_ObjectProperties(MM_ObjectProperty entity)
		{
			this.SendPropertyChanging();
			entity.MM_ObjectType = this;
		}
		
		private void detach_MM_ObjectProperties(MM_ObjectProperty entity)
		{
			this.SendPropertyChanging();
			entity.MM_ObjectType = null;
		}
		
		private void attach_MM_ObjectProperties1(MM_ObjectProperty entity)
		{
			this.SendPropertyChanging();
			entity.RefObjectType = this;
		}
		
		private void detach_MM_ObjectProperties1(MM_ObjectProperty entity)
		{
			this.SendPropertyChanging();
			entity.RefObjectType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MM_ObjectProperty")]
	public partial class MM_ObjectProperty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ObjectPropertyID;
		
		private int _ObjectTypeID;
		
		private string _Title;
		
		private string _SysName;
		
		private int _SeqNo;
		
		private string _TypeCode;
		
		private System.Guid _Guid;
		
		private bool _IsMultilingual;
		
		private bool _IsPrimaryKey;
		
		private bool _IsSystem;
		
		private System.Nullable<int> _RefObjectPropertyID;
		
		private System.Nullable<int> _RefObjectTypeID;
		
		private bool _IsNavigable;
		
		private bool _IsAggregate;
		
		private int _LowerBound;
		
		private int _UpperBound;
		
		private System.Nullable<int> _CodifierID;
		
		private string _Expression;
		
		private bool _IsReferenceToVersion;
		
		private string _ValueFilter;
		
		private System.Nullable<int> _Precision;
		
		private System.Nullable<int> _Scale;
		
		private System.Nullable<int> _Length;
		
		private string _DeleteRule;
		
		private string _KindCode;
		
		private EntitySet<MM_ObjectProperty> _MM_ObjectProperties;
		
		private EntityRef<MM_ObjectType> _MM_ObjectType;
		
		private EntityRef<MM_ObjectType> _RefObjectType;
		
		private EntityRef<MM_ObjectProperty> _MM_ObjectProperty1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnObjectPropertyIDChanging(int value);
    partial void OnObjectPropertyIDChanged();
    partial void OnObjectTypeIDChanging(int value);
    partial void OnObjectTypeIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnSysNameChanging(string value);
    partial void OnSysNameChanged();
    partial void OnSeqNoChanging(int value);
    partial void OnSeqNoChanged();
    partial void OnTypeCodeChanging(string value);
    partial void OnTypeCodeChanged();
    partial void OnGuidChanging(System.Guid value);
    partial void OnGuidChanged();
    partial void OnIsMultilingualChanging(bool value);
    partial void OnIsMultilingualChanged();
    partial void OnIsPrimaryKeyChanging(bool value);
    partial void OnIsPrimaryKeyChanged();
    partial void OnIsSystemChanging(bool value);
    partial void OnIsSystemChanged();
    partial void OnRefObjectPropertyIDChanging(System.Nullable<int> value);
    partial void OnRefObjectPropertyIDChanged();
    partial void OnRefObjectTypeIDChanging(System.Nullable<int> value);
    partial void OnRefObjectTypeIDChanged();
    partial void OnIsNavigableChanging(bool value);
    partial void OnIsNavigableChanged();
    partial void OnIsAggregateChanging(bool value);
    partial void OnIsAggregateChanged();
    partial void OnLowerBoundChanging(int value);
    partial void OnLowerBoundChanged();
    partial void OnUpperBoundChanging(int value);
    partial void OnUpperBoundChanged();
    partial void OnCodifierIDChanging(System.Nullable<int> value);
    partial void OnCodifierIDChanged();
    partial void OnExpressionChanging(string value);
    partial void OnExpressionChanged();
    partial void OnIsReferenceToVersionChanging(bool value);
    partial void OnIsReferenceToVersionChanged();
    partial void OnValueFilterChanging(string value);
    partial void OnValueFilterChanged();
    partial void OnPrecisionChanging(System.Nullable<int> value);
    partial void OnPrecisionChanged();
    partial void OnScaleChanging(System.Nullable<int> value);
    partial void OnScaleChanged();
    partial void OnLengthChanging(System.Nullable<int> value);
    partial void OnLengthChanged();
    partial void OnDeleteRuleChanging(string value);
    partial void OnDeleteRuleChanged();
    partial void OnKindCodeChanging(string value);
    partial void OnKindCodeChanged();
    #endregion
		
		public MM_ObjectProperty()
		{
			this._MM_ObjectProperties = new EntitySet<MM_ObjectProperty>(new Action<MM_ObjectProperty>(this.attach_MM_ObjectProperties), new Action<MM_ObjectProperty>(this.detach_MM_ObjectProperties));
			this._MM_ObjectType = default(EntityRef<MM_ObjectType>);
			this._RefObjectType = default(EntityRef<MM_ObjectType>);
			this._MM_ObjectProperty1 = default(EntityRef<MM_ObjectProperty>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectPropertyID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ObjectPropertyID
		{
			get
			{
				return this._ObjectPropertyID;
			}
			set
			{
				if ((this._ObjectPropertyID != value))
				{
					this.OnObjectPropertyIDChanging(value);
					this.SendPropertyChanging();
					this._ObjectPropertyID = value;
					this.SendPropertyChanged("ObjectPropertyID");
					this.OnObjectPropertyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectTypeID", DbType="Int NOT NULL")]
		public int ObjectTypeID
		{
			get
			{
				return this._ObjectTypeID;
			}
			set
			{
				if ((this._ObjectTypeID != value))
				{
					if (this._MM_ObjectType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnObjectTypeIDChanging(value);
					this.SendPropertyChanging();
					this._ObjectTypeID = value;
					this.SendPropertyChanged("ObjectTypeID");
					this.OnObjectTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(1024) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string SysName
		{
			get
			{
				return this._SysName;
			}
			set
			{
				if ((this._SysName != value))
				{
					this.OnSysNameChanging(value);
					this.SendPropertyChanging();
					this._SysName = value;
					this.SendPropertyChanged("SysName");
					this.OnSysNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeqNo", DbType="Int NOT NULL")]
		public int SeqNo
		{
			get
			{
				return this._SeqNo;
			}
			set
			{
				if ((this._SeqNo != value))
				{
					this.OnSeqNoChanging(value);
					this.SendPropertyChanging();
					this._SeqNo = value;
					this.SendPropertyChanged("SeqNo");
					this.OnSeqNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeCode", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string TypeCode
		{
			get
			{
				return this._TypeCode;
			}
			set
			{
				if ((this._TypeCode != value))
				{
					this.OnTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._TypeCode = value;
					this.SendPropertyChanged("TypeCode");
					this.OnTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Guid
		{
			get
			{
				return this._Guid;
			}
			set
			{
				if ((this._Guid != value))
				{
					this.OnGuidChanging(value);
					this.SendPropertyChanging();
					this._Guid = value;
					this.SendPropertyChanged("Guid");
					this.OnGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMultilingual", DbType="Bit NOT NULL")]
		public bool IsMultilingual
		{
			get
			{
				return this._IsMultilingual;
			}
			set
			{
				if ((this._IsMultilingual != value))
				{
					this.OnIsMultilingualChanging(value);
					this.SendPropertyChanging();
					this._IsMultilingual = value;
					this.SendPropertyChanged("IsMultilingual");
					this.OnIsMultilingualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrimaryKey", DbType="Bit NOT NULL")]
		public bool IsPrimaryKey
		{
			get
			{
				return this._IsPrimaryKey;
			}
			set
			{
				if ((this._IsPrimaryKey != value))
				{
					this.OnIsPrimaryKeyChanging(value);
					this.SendPropertyChanging();
					this._IsPrimaryKey = value;
					this.SendPropertyChanged("IsPrimaryKey");
					this.OnIsPrimaryKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSystem", DbType="Bit NOT NULL")]
		public bool IsSystem
		{
			get
			{
				return this._IsSystem;
			}
			set
			{
				if ((this._IsSystem != value))
				{
					this.OnIsSystemChanging(value);
					this.SendPropertyChanging();
					this._IsSystem = value;
					this.SendPropertyChanged("IsSystem");
					this.OnIsSystemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefObjectPropertyID", DbType="Int")]
		public System.Nullable<int> RefObjectPropertyID
		{
			get
			{
				return this._RefObjectPropertyID;
			}
			set
			{
				if ((this._RefObjectPropertyID != value))
				{
					if (this._MM_ObjectProperty1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRefObjectPropertyIDChanging(value);
					this.SendPropertyChanging();
					this._RefObjectPropertyID = value;
					this.SendPropertyChanged("RefObjectPropertyID");
					this.OnRefObjectPropertyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefObjectTypeID", DbType="Int")]
		public System.Nullable<int> RefObjectTypeID
		{
			get
			{
				return this._RefObjectTypeID;
			}
			set
			{
				if ((this._RefObjectTypeID != value))
				{
					if (this._RefObjectType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRefObjectTypeIDChanging(value);
					this.SendPropertyChanging();
					this._RefObjectTypeID = value;
					this.SendPropertyChanged("RefObjectTypeID");
					this.OnRefObjectTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNavigable", DbType="Bit NOT NULL")]
		public bool IsNavigable
		{
			get
			{
				return this._IsNavigable;
			}
			set
			{
				if ((this._IsNavigable != value))
				{
					this.OnIsNavigableChanging(value);
					this.SendPropertyChanging();
					this._IsNavigable = value;
					this.SendPropertyChanged("IsNavigable");
					this.OnIsNavigableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAggregate", DbType="Bit NOT NULL")]
		public bool IsAggregate
		{
			get
			{
				return this._IsAggregate;
			}
			set
			{
				if ((this._IsAggregate != value))
				{
					this.OnIsAggregateChanging(value);
					this.SendPropertyChanging();
					this._IsAggregate = value;
					this.SendPropertyChanged("IsAggregate");
					this.OnIsAggregateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowerBound", DbType="Int NOT NULL")]
		public int LowerBound
		{
			get
			{
				return this._LowerBound;
			}
			set
			{
				if ((this._LowerBound != value))
				{
					this.OnLowerBoundChanging(value);
					this.SendPropertyChanging();
					this._LowerBound = value;
					this.SendPropertyChanged("LowerBound");
					this.OnLowerBoundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpperBound", DbType="Int NOT NULL")]
		public int UpperBound
		{
			get
			{
				return this._UpperBound;
			}
			set
			{
				if ((this._UpperBound != value))
				{
					this.OnUpperBoundChanging(value);
					this.SendPropertyChanging();
					this._UpperBound = value;
					this.SendPropertyChanged("UpperBound");
					this.OnUpperBoundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodifierID", DbType="Int")]
		public System.Nullable<int> CodifierID
		{
			get
			{
				return this._CodifierID;
			}
			set
			{
				if ((this._CodifierID != value))
				{
					this.OnCodifierIDChanging(value);
					this.SendPropertyChanging();
					this._CodifierID = value;
					this.SendPropertyChanged("CodifierID");
					this.OnCodifierIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expression", DbType="NVarChar(MAX)")]
		public string Expression
		{
			get
			{
				return this._Expression;
			}
			set
			{
				if ((this._Expression != value))
				{
					this.OnExpressionChanging(value);
					this.SendPropertyChanging();
					this._Expression = value;
					this.SendPropertyChanged("Expression");
					this.OnExpressionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReferenceToVersion", DbType="Bit NOT NULL")]
		public bool IsReferenceToVersion
		{
			get
			{
				return this._IsReferenceToVersion;
			}
			set
			{
				if ((this._IsReferenceToVersion != value))
				{
					this.OnIsReferenceToVersionChanging(value);
					this.SendPropertyChanging();
					this._IsReferenceToVersion = value;
					this.SendPropertyChanged("IsReferenceToVersion");
					this.OnIsReferenceToVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueFilter", DbType="NVarChar(MAX)")]
		public string ValueFilter
		{
			get
			{
				return this._ValueFilter;
			}
			set
			{
				if ((this._ValueFilter != value))
				{
					this.OnValueFilterChanging(value);
					this.SendPropertyChanging();
					this._ValueFilter = value;
					this.SendPropertyChanged("ValueFilter");
					this.OnValueFilterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precision", DbType="Int")]
		public System.Nullable<int> Precision
		{
			get
			{
				return this._Precision;
			}
			set
			{
				if ((this._Precision != value))
				{
					this.OnPrecisionChanging(value);
					this.SendPropertyChanging();
					this._Precision = value;
					this.SendPropertyChanged("Precision");
					this.OnPrecisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scale", DbType="Int")]
		public System.Nullable<int> Scale
		{
			get
			{
				return this._Scale;
			}
			set
			{
				if ((this._Scale != value))
				{
					this.OnScaleChanging(value);
					this.SendPropertyChanging();
					this._Scale = value;
					this.SendPropertyChanged("Scale");
					this.OnScaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Length", DbType="Int")]
		public System.Nullable<int> Length
		{
			get
			{
				return this._Length;
			}
			set
			{
				if ((this._Length != value))
				{
					this.OnLengthChanging(value);
					this.SendPropertyChanging();
					this._Length = value;
					this.SendPropertyChanged("Length");
					this.OnLengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteRule", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string DeleteRule
		{
			get
			{
				return this._DeleteRule;
			}
			set
			{
				if ((this._DeleteRule != value))
				{
					this.OnDeleteRuleChanging(value);
					this.SendPropertyChanging();
					this._DeleteRule = value;
					this.SendPropertyChanged("DeleteRule");
					this.OnDeleteRuleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KindCode", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string KindCode
		{
			get
			{
				return this._KindCode;
			}
			set
			{
				if ((this._KindCode != value))
				{
					this.OnKindCodeChanging(value);
					this.SendPropertyChanging();
					this._KindCode = value;
					this.SendPropertyChanged("KindCode");
					this.OnKindCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MM_ObjectProperty_MM_ObjectProperty", Storage="_MM_ObjectProperties", ThisKey="ObjectPropertyID", OtherKey="RefObjectPropertyID")]
		public EntitySet<MM_ObjectProperty> MM_ObjectProperties
		{
			get
			{
				return this._MM_ObjectProperties;
			}
			set
			{
				this._MM_ObjectProperties.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MM_ObjectType_MM_ObjectProperty", Storage="_MM_ObjectType", ThisKey="ObjectTypeID", OtherKey="ObjectTypeID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public MM_ObjectType MM_ObjectType
		{
			get
			{
				return this._MM_ObjectType.Entity;
			}
			set
			{
				MM_ObjectType previousValue = this._MM_ObjectType.Entity;
				if (((previousValue != value) 
							|| (this._MM_ObjectType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MM_ObjectType.Entity = null;
						previousValue.MM_ObjectProperties.Remove(this);
					}
					this._MM_ObjectType.Entity = value;
					if ((value != null))
					{
						value.MM_ObjectProperties.Add(this);
						this._ObjectTypeID = value.ObjectTypeID;
					}
					else
					{
						this._ObjectTypeID = default(int);
					}
					this.SendPropertyChanged("MM_ObjectType");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MM_ObjectType_MM_ObjectProperty1", Storage="_RefObjectType", ThisKey="RefObjectTypeID", OtherKey="ObjectTypeID", IsForeignKey=true)]
		public MM_ObjectType RefObjectType
		{
			get
			{
				return this._RefObjectType.Entity;
			}
			set
			{
				MM_ObjectType previousValue = this._RefObjectType.Entity;
				if (((previousValue != value) 
							|| (this._RefObjectType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RefObjectType.Entity = null;
						previousValue.MM_ObjectProperties1.Remove(this);
					}
					this._RefObjectType.Entity = value;
					if ((value != null))
					{
						value.MM_ObjectProperties1.Add(this);
						this._RefObjectTypeID = value.ObjectTypeID;
					}
					else
					{
						this._RefObjectTypeID = default(Nullable<int>);
					}
					this.SendPropertyChanged("RefObjectType");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MM_ObjectProperty_MM_ObjectProperty", Storage="_MM_ObjectProperty1", ThisKey="RefObjectPropertyID", OtherKey="ObjectPropertyID", IsForeignKey=true)]
		public MM_ObjectProperty MM_ObjectProperty1
		{
			get
			{
				return this._MM_ObjectProperty1.Entity;
			}
			set
			{
				MM_ObjectProperty previousValue = this._MM_ObjectProperty1.Entity;
				if (((previousValue != value) 
							|| (this._MM_ObjectProperty1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MM_ObjectProperty1.Entity = null;
						previousValue.MM_ObjectProperties.Remove(this);
					}
					this._MM_ObjectProperty1.Entity = value;
					if ((value != null))
					{
						value.MM_ObjectProperties.Add(this);
						this._RefObjectPropertyID = value.ObjectPropertyID;
					}
					else
					{
						this._RefObjectPropertyID = default(Nullable<int>);
					}
					this.SendPropertyChanged("MM_ObjectProperty1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MM_ObjectProperties(MM_ObjectProperty entity)
		{
			this.SendPropertyChanging();
			entity.MM_ObjectProperty1 = this;
		}
		
		private void detach_MM_ObjectProperties(MM_ObjectProperty entity)
		{
			this.SendPropertyChanging();
			entity.MM_ObjectProperty1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SiteInfoobjects")]
	public partial class SiteInfoobject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SiteInfoobjectsID;
		
		private System.Nullable<bool> _IsFolder;
		
		private System.Nullable<bool> _IsRoot;
		
		private EntityRef<MM_ObjectType> _MM_ObjectType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSiteInfoobjectsIDChanging(int value);
    partial void OnSiteInfoobjectsIDChanged();
    partial void OnIsFolderChanging(System.Nullable<bool> value);
    partial void OnIsFolderChanged();
    partial void OnIsRootChanging(System.Nullable<bool> value);
    partial void OnIsRootChanged();
    #endregion
		
		public SiteInfoobject()
		{
			this._MM_ObjectType = default(EntityRef<MM_ObjectType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteInfoobjectsID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SiteInfoobjectsID
		{
			get
			{
				return this._SiteInfoobjectsID;
			}
			set
			{
				if ((this._SiteInfoobjectsID != value))
				{
					if (this._MM_ObjectType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSiteInfoobjectsIDChanging(value);
					this.SendPropertyChanging();
					this._SiteInfoobjectsID = value;
					this.SendPropertyChanged("SiteInfoobjectsID");
					this.OnSiteInfoobjectsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFolder", DbType="Bit")]
		public System.Nullable<bool> IsFolder
		{
			get
			{
				return this._IsFolder;
			}
			set
			{
				if ((this._IsFolder != value))
				{
					this.OnIsFolderChanging(value);
					this.SendPropertyChanging();
					this._IsFolder = value;
					this.SendPropertyChanged("IsFolder");
					this.OnIsFolderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRoot", DbType="Bit")]
		public System.Nullable<bool> IsRoot
		{
			get
			{
				return this._IsRoot;
			}
			set
			{
				if ((this._IsRoot != value))
				{
					this.OnIsRootChanging(value);
					this.SendPropertyChanging();
					this._IsRoot = value;
					this.SendPropertyChanged("IsRoot");
					this.OnIsRootChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MM_ObjectType_SiteInfoobject", Storage="_MM_ObjectType", ThisKey="SiteInfoobjectsID", OtherKey="ObjectTypeID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public MM_ObjectType MM_ObjectType
		{
			get
			{
				return this._MM_ObjectType.Entity;
			}
			set
			{
				MM_ObjectType previousValue = this._MM_ObjectType.Entity;
				if (((previousValue != value) 
							|| (this._MM_ObjectType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MM_ObjectType.Entity = null;
						previousValue.SiteInfoobject = null;
					}
					this._MM_ObjectType.Entity = value;
					if ((value != null))
					{
						value.SiteInfoobject = this;
						this._SiteInfoobjectsID = value.ObjectTypeID;
					}
					else
					{
						this._SiteInfoobjectsID = default(int);
					}
					this.SendPropertyChanged("MM_ObjectType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SiteSection")]
	public partial class SiteSection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SiteSectionID;
		
		private bool _IsDeleted;
		
		private System.DateTime _LastModifiedDate;
		
		private int _LastModifiedUserID;
		
		private System.Nullable<int> _ParentID;
		
		private System.DateTime _CreateDate;
		
		private int _SeqNo;
		
		private string _SysName;
		
		private System.Nullable<System.DateTime> _PublishDate;
		
		private bool _ShowInSiteMap;
		
		private bool _ShowInNavigation;
		
		private bool _IsPublished;
		
		private string _ViewName;
		
		private string _SiteObjectsClasses;
		
		private EntitySet<SiteSection> _SiteSections;
		
		private EntitySet<SiteObject> _SiteObjects;
		
		private EntityRef<SiteSection> _SiteSection1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSiteSectionIDChanging(int value);
    partial void OnSiteSectionIDChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnLastModifiedDateChanging(System.DateTime value);
    partial void OnLastModifiedDateChanged();
    partial void OnLastModifiedUserIDChanging(int value);
    partial void OnLastModifiedUserIDChanged();
    partial void OnParentIDChanging(System.Nullable<int> value);
    partial void OnParentIDChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnSeqNoChanging(int value);
    partial void OnSeqNoChanged();
    partial void OnSysNameChanging(string value);
    partial void OnSysNameChanged();
    partial void OnPublishDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPublishDateChanged();
    partial void OnShowInSiteMapChanging(bool value);
    partial void OnShowInSiteMapChanged();
    partial void OnShowInNavigationChanging(bool value);
    partial void OnShowInNavigationChanged();
    partial void OnIsPublishedChanging(bool value);
    partial void OnIsPublishedChanged();
    partial void OnViewNameChanging(string value);
    partial void OnViewNameChanged();
    partial void OnSiteObjectsClassesChanging(string value);
    partial void OnSiteObjectsClassesChanged();
    #endregion
		
		public SiteSection()
		{
			this._SiteSections = new EntitySet<SiteSection>(new Action<SiteSection>(this.attach_SiteSections), new Action<SiteSection>(this.detach_SiteSections));
			this._SiteObjects = new EntitySet<SiteObject>(new Action<SiteObject>(this.attach_SiteObjects), new Action<SiteObject>(this.detach_SiteObjects));
			this._SiteSection1 = default(EntityRef<SiteSection>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteSectionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SiteSectionID
		{
			get
			{
				return this._SiteSectionID;
			}
			set
			{
				if ((this._SiteSectionID != value))
				{
					this.OnSiteSectionIDChanging(value);
					this.SendPropertyChanging();
					this._SiteSectionID = value;
					this.SendPropertyChanged("SiteSectionID");
					this.OnSiteSectionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastModifiedDate
		{
			get
			{
				return this._LastModifiedDate;
			}
			set
			{
				if ((this._LastModifiedDate != value))
				{
					this.OnLastModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedDate = value;
					this.SendPropertyChanged("LastModifiedDate");
					this.OnLastModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedUserID", DbType="Int NOT NULL")]
		public int LastModifiedUserID
		{
			get
			{
				return this._LastModifiedUserID;
			}
			set
			{
				if ((this._LastModifiedUserID != value))
				{
					this.OnLastModifiedUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedUserID = value;
					this.SendPropertyChanged("LastModifiedUserID");
					this.OnLastModifiedUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
		public System.Nullable<int> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					if (this._SiteSection1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnParentIDChanging(value);
					this.SendPropertyChanging();
					this._ParentID = value;
					this.SendPropertyChanged("ParentID");
					this.OnParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeqNo", DbType="Int NOT NULL")]
		public int SeqNo
		{
			get
			{
				return this._SeqNo;
			}
			set
			{
				if ((this._SeqNo != value))
				{
					this.OnSeqNoChanging(value);
					this.SendPropertyChanging();
					this._SeqNo = value;
					this.SendPropertyChanged("SeqNo");
					this.OnSeqNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysName", DbType="NVarChar(255)")]
		public string SysName
		{
			get
			{
				return this._SysName;
			}
			set
			{
				if ((this._SysName != value))
				{
					this.OnSysNameChanging(value);
					this.SendPropertyChanging();
					this._SysName = value;
					this.SendPropertyChanged("SysName");
					this.OnSysNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishDate
		{
			get
			{
				return this._PublishDate;
			}
			set
			{
				if ((this._PublishDate != value))
				{
					this.OnPublishDateChanging(value);
					this.SendPropertyChanging();
					this._PublishDate = value;
					this.SendPropertyChanged("PublishDate");
					this.OnPublishDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowInSiteMap", DbType="Bit NOT NULL")]
		public bool ShowInSiteMap
		{
			get
			{
				return this._ShowInSiteMap;
			}
			set
			{
				if ((this._ShowInSiteMap != value))
				{
					this.OnShowInSiteMapChanging(value);
					this.SendPropertyChanging();
					this._ShowInSiteMap = value;
					this.SendPropertyChanged("ShowInSiteMap");
					this.OnShowInSiteMapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowInNavigation", DbType="Bit NOT NULL")]
		public bool ShowInNavigation
		{
			get
			{
				return this._ShowInNavigation;
			}
			set
			{
				if ((this._ShowInNavigation != value))
				{
					this.OnShowInNavigationChanging(value);
					this.SendPropertyChanging();
					this._ShowInNavigation = value;
					this.SendPropertyChanged("ShowInNavigation");
					this.OnShowInNavigationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this.OnIsPublishedChanging(value);
					this.SendPropertyChanging();
					this._IsPublished = value;
					this.SendPropertyChanged("IsPublished");
					this.OnIsPublishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewName", DbType="NVarChar(MAX)")]
		public string ViewName
		{
			get
			{
				return this._ViewName;
			}
			set
			{
				if ((this._ViewName != value))
				{
					this.OnViewNameChanging(value);
					this.SendPropertyChanging();
					this._ViewName = value;
					this.SendPropertyChanged("ViewName");
					this.OnViewNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteObjectsClasses", DbType="NVarChar(MAX)")]
		public string SiteObjectsClasses
		{
			get
			{
				return this._SiteObjectsClasses;
			}
			set
			{
				if ((this._SiteObjectsClasses != value))
				{
					this.OnSiteObjectsClassesChanging(value);
					this.SendPropertyChanging();
					this._SiteObjectsClasses = value;
					this.SendPropertyChanged("SiteObjectsClasses");
					this.OnSiteObjectsClassesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SiteSection_SiteSection", Storage="_SiteSections", ThisKey="SiteSectionID", OtherKey="ParentID")]
		public EntitySet<SiteSection> SiteSections
		{
			get
			{
				return this._SiteSections;
			}
			set
			{
				this._SiteSections.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SiteSection_SiteObject", Storage="_SiteObjects", ThisKey="SiteSectionID", OtherKey="ParentID")]
		public EntitySet<SiteObject> SiteObjects
		{
			get
			{
				return this._SiteObjects;
			}
			set
			{
				this._SiteObjects.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SiteSection_SiteSection", Storage="_SiteSection1", ThisKey="ParentID", OtherKey="SiteSectionID", IsForeignKey=true)]
		public SiteSection SiteSection1
		{
			get
			{
				return this._SiteSection1.Entity;
			}
			set
			{
				SiteSection previousValue = this._SiteSection1.Entity;
				if (((previousValue != value) 
							|| (this._SiteSection1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SiteSection1.Entity = null;
						previousValue.SiteSections.Remove(this);
					}
					this._SiteSection1.Entity = value;
					if ((value != null))
					{
						value.SiteSections.Add(this);
						this._ParentID = value.SiteSectionID;
					}
					else
					{
						this._ParentID = default(Nullable<int>);
					}
					this.SendPropertyChanged("SiteSection1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SiteSections(SiteSection entity)
		{
			this.SendPropertyChanging();
			entity.SiteSection1 = this;
		}
		
		private void detach_SiteSections(SiteSection entity)
		{
			this.SendPropertyChanging();
			entity.SiteSection1 = null;
		}
		
		private void attach_SiteObjects(SiteObject entity)
		{
			this.SendPropertyChanging();
			entity.SiteSection = this;
		}
		
		private void detach_SiteObjects(SiteObject entity)
		{
			this.SendPropertyChanging();
			entity.SiteSection = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SiteObject")]
	public partial class SiteObject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SiteObjectID;
		
		private bool _IsDeleted;
		
		private System.DateTime _LastModifiedDate;
		
		private int _LastModifiedUserID;
		
		private int _SeqNo;
		
		private int _ParentID;
		
		private string _ClassName;
		
		private bool _IsPublished;
		
		private System.DateTime _CreateDate;
		
		private System.Nullable<System.DateTime> _PublishDate;
		
		private EntityRef<SiteSection> _SiteSection;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSiteObjectIDChanging(int value);
    partial void OnSiteObjectIDChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnLastModifiedDateChanging(System.DateTime value);
    partial void OnLastModifiedDateChanged();
    partial void OnLastModifiedUserIDChanging(int value);
    partial void OnLastModifiedUserIDChanged();
    partial void OnSeqNoChanging(int value);
    partial void OnSeqNoChanged();
    partial void OnParentIDChanging(int value);
    partial void OnParentIDChanged();
    partial void OnClassNameChanging(string value);
    partial void OnClassNameChanged();
    partial void OnIsPublishedChanging(bool value);
    partial void OnIsPublishedChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnPublishDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPublishDateChanged();
    #endregion
		
		public SiteObject()
		{
			this._SiteSection = default(EntityRef<SiteSection>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteObjectID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SiteObjectID
		{
			get
			{
				return this._SiteObjectID;
			}
			set
			{
				if ((this._SiteObjectID != value))
				{
					this.OnSiteObjectIDChanging(value);
					this.SendPropertyChanging();
					this._SiteObjectID = value;
					this.SendPropertyChanged("SiteObjectID");
					this.OnSiteObjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastModifiedDate
		{
			get
			{
				return this._LastModifiedDate;
			}
			set
			{
				if ((this._LastModifiedDate != value))
				{
					this.OnLastModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedDate = value;
					this.SendPropertyChanged("LastModifiedDate");
					this.OnLastModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedUserID", DbType="Int NOT NULL")]
		public int LastModifiedUserID
		{
			get
			{
				return this._LastModifiedUserID;
			}
			set
			{
				if ((this._LastModifiedUserID != value))
				{
					this.OnLastModifiedUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedUserID = value;
					this.SendPropertyChanged("LastModifiedUserID");
					this.OnLastModifiedUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeqNo", DbType="Int NOT NULL")]
		public int SeqNo
		{
			get
			{
				return this._SeqNo;
			}
			set
			{
				if ((this._SeqNo != value))
				{
					this.OnSeqNoChanging(value);
					this.SendPropertyChanging();
					this._SeqNo = value;
					this.SendPropertyChanged("SeqNo");
					this.OnSeqNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int NOT NULL")]
		public int ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					if (this._SiteSection.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnParentIDChanging(value);
					this.SendPropertyChanging();
					this._ParentID = value;
					this.SendPropertyChanged("ParentID");
					this.OnParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ClassName
		{
			get
			{
				return this._ClassName;
			}
			set
			{
				if ((this._ClassName != value))
				{
					this.OnClassNameChanging(value);
					this.SendPropertyChanging();
					this._ClassName = value;
					this.SendPropertyChanged("ClassName");
					this.OnClassNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this.OnIsPublishedChanging(value);
					this.SendPropertyChanging();
					this._IsPublished = value;
					this.SendPropertyChanged("IsPublished");
					this.OnIsPublishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishDate
		{
			get
			{
				return this._PublishDate;
			}
			set
			{
				if ((this._PublishDate != value))
				{
					this.OnPublishDateChanging(value);
					this.SendPropertyChanging();
					this._PublishDate = value;
					this.SendPropertyChanged("PublishDate");
					this.OnPublishDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SiteSection_SiteObject", Storage="_SiteSection", ThisKey="ParentID", OtherKey="SiteSectionID", IsForeignKey=true)]
		public SiteSection SiteSection
		{
			get
			{
				return this._SiteSection.Entity;
			}
			set
			{
				SiteSection previousValue = this._SiteSection.Entity;
				if (((previousValue != value) 
							|| (this._SiteSection.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SiteSection.Entity = null;
						previousValue.SiteObjects.Remove(this);
					}
					this._SiteSection.Entity = value;
					if ((value != null))
					{
						value.SiteObjects.Add(this);
						this._ParentID = value.SiteSectionID;
					}
					else
					{
						this._ParentID = default(int);
					}
					this.SendPropertyChanged("SiteSection");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_SiteObject")]
	public partial class V_SiteObject
	{
		
		private int _SiteObjectID;
		
		private bool _IsDeleted;
		
		private System.DateTime _LastModifiedDate;
		
		private int _LastModifiedUserID;
		
		private int _SeqNo;
		
		private int _ParentID;
		
		private string _ClassName;
		
		private bool _IsPublished;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _PublishDate;
		
		private string _LanguageCode;
		
		private string _Title;
		
		private string _SubTitle;
		
		public V_SiteObject()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteObjectID", DbType="Int NOT NULL")]
		public int SiteObjectID
		{
			get
			{
				return this._SiteObjectID;
			}
			set
			{
				if ((this._SiteObjectID != value))
				{
					this._SiteObjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastModifiedDate
		{
			get
			{
				return this._LastModifiedDate;
			}
			set
			{
				if ((this._LastModifiedDate != value))
				{
					this._LastModifiedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedUserID", DbType="Int NOT NULL")]
		public int LastModifiedUserID
		{
			get
			{
				return this._LastModifiedUserID;
			}
			set
			{
				if ((this._LastModifiedUserID != value))
				{
					this._LastModifiedUserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeqNo", DbType="Int NOT NULL")]
		public int SeqNo
		{
			get
			{
				return this._SeqNo;
			}
			set
			{
				if ((this._SeqNo != value))
				{
					this._SeqNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int NOT NULL")]
		public int ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ClassName
		{
			get
			{
				return this._ClassName;
			}
			set
			{
				if ((this._ClassName != value))
				{
					this._ClassName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this._IsPublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishDate
		{
			get
			{
				return this._PublishDate;
			}
			set
			{
				if ((this._PublishDate != value))
				{
					this._PublishDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NChar(2) NOT NULL", CanBeNull=false)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this._LanguageCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTitle", DbType="NVarChar(MAX)")]
		public string SubTitle
		{
			get
			{
				return this._SubTitle;
			}
			set
			{
				if ((this._SubTitle != value))
				{
					this._SubTitle = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_SiteSection")]
	public partial class V_SiteSection
	{
		
		private int _SiteSectionID;
		
		private bool _IsDeleted;
		
		private System.DateTime _LastModifiedDate;
		
		private int _LastModifiedUserID;
		
		private System.Nullable<int> _ParentID;
		
		private System.DateTime _CreateDate;
		
		private int _SeqNo;
		
		private string _SysName;
		
		private System.Nullable<System.DateTime> _PublishDate;
		
		private bool _ShowInSiteMap;
		
		private bool _ShowInNavigation;
		
		private bool _IsPublished;
		
		private string _SiteObjectsClasses;
		
		private string _ViewName;
		
		private string _Description;
		
		private string _Keywords;
		
		private string _PageTitle;
		
		private string _LanguageCode;
		
		private string _Title;
		
		private string _FullPath;
		
		public V_SiteSection()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteSectionID", DbType="Int NOT NULL")]
		public int SiteSectionID
		{
			get
			{
				return this._SiteSectionID;
			}
			set
			{
				if ((this._SiteSectionID != value))
				{
					this._SiteSectionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastModifiedDate
		{
			get
			{
				return this._LastModifiedDate;
			}
			set
			{
				if ((this._LastModifiedDate != value))
				{
					this._LastModifiedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedUserID", DbType="Int NOT NULL")]
		public int LastModifiedUserID
		{
			get
			{
				return this._LastModifiedUserID;
			}
			set
			{
				if ((this._LastModifiedUserID != value))
				{
					this._LastModifiedUserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
		public System.Nullable<int> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeqNo", DbType="Int NOT NULL")]
		public int SeqNo
		{
			get
			{
				return this._SeqNo;
			}
			set
			{
				if ((this._SeqNo != value))
				{
					this._SeqNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysName", DbType="NVarChar(255)")]
		public string SysName
		{
			get
			{
				return this._SysName;
			}
			set
			{
				if ((this._SysName != value))
				{
					this._SysName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishDate
		{
			get
			{
				return this._PublishDate;
			}
			set
			{
				if ((this._PublishDate != value))
				{
					this._PublishDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowInSiteMap", DbType="Bit NOT NULL")]
		public bool ShowInSiteMap
		{
			get
			{
				return this._ShowInSiteMap;
			}
			set
			{
				if ((this._ShowInSiteMap != value))
				{
					this._ShowInSiteMap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowInNavigation", DbType="Bit NOT NULL")]
		public bool ShowInNavigation
		{
			get
			{
				return this._ShowInNavigation;
			}
			set
			{
				if ((this._ShowInNavigation != value))
				{
					this._ShowInNavigation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this._IsPublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteObjectsClasses", DbType="NVarChar(MAX)")]
		public string SiteObjectsClasses
		{
			get
			{
				return this._SiteObjectsClasses;
			}
			set
			{
				if ((this._SiteObjectsClasses != value))
				{
					this._SiteObjectsClasses = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewName", DbType="NVarChar(MAX)")]
		public string ViewName
		{
			get
			{
				return this._ViewName;
			}
			set
			{
				if ((this._ViewName != value))
				{
					this._ViewName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keywords", DbType="NVarChar(MAX)")]
		public string Keywords
		{
			get
			{
				return this._Keywords;
			}
			set
			{
				if ((this._Keywords != value))
				{
					this._Keywords = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageTitle", DbType="NVarChar(MAX)")]
		public string PageTitle
		{
			get
			{
				return this._PageTitle;
			}
			set
			{
				if ((this._PageTitle != value))
				{
					this._PageTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="NChar(2) NOT NULL", CanBeNull=false)]
		public string LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this._LanguageCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(512)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullPath", DbType="NVarChar(MAX)")]
		public string FullPath
		{
			get
			{
				return this._FullPath;
			}
			set
			{
				if ((this._FullPath != value))
				{
					this._FullPath = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
