//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nephrite.Web.TaskManagerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nephritetech.com/tessera/integration/1.0", ConfigurationName="TaskManagerServiceReference.TaskManagerService")]
    public interface TaskManagerService {
        
        // CODEGEN: Generating message contract since message RunTasksRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://nephritetech.com/tessera/integration/1.0/RunTasks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nephrite.Web.TaskManagerServiceReference.RunTasksResponse RunTasks(Nephrite.Web.TaskManagerServiceReference.RunTasksRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nephritetech.com/tessera/integration/1.0")]
    public partial class UserCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("Login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RunTasks", WrapperNamespace="http://nephritetech.com/tessera/integration/1.0", IsWrapped=true)]
    public partial class RunTasksRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://nephritetech.com/tessera/integration/1.0")]
        public Nephrite.Web.TaskManagerServiceReference.UserCredentials UserCredentials;
        
        public RunTasksRequest() {
        }
        
        public RunTasksRequest(Nephrite.Web.TaskManagerServiceReference.UserCredentials UserCredentials) {
            this.UserCredentials = UserCredentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RunTasksResponse", WrapperNamespace="http://nephritetech.com/tessera/integration/1.0", IsWrapped=true)]
    public partial class RunTasksResponse {
        
        public RunTasksResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TaskManagerServiceChannel : Nephrite.Web.TaskManagerServiceReference.TaskManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskManagerServiceClient : System.ServiceModel.ClientBase<Nephrite.Web.TaskManagerServiceReference.TaskManagerService>, Nephrite.Web.TaskManagerServiceReference.TaskManagerService {
        
        public TaskManagerServiceClient() {
        }
        
        public TaskManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nephrite.Web.TaskManagerServiceReference.RunTasksResponse Nephrite.Web.TaskManagerServiceReference.TaskManagerService.RunTasks(Nephrite.Web.TaskManagerServiceReference.RunTasksRequest request) {
            return base.Channel.RunTasks(request);
        }
        
        public void RunTasks(Nephrite.Web.TaskManagerServiceReference.UserCredentials UserCredentials) {
            Nephrite.Web.TaskManagerServiceReference.RunTasksRequest inValue = new Nephrite.Web.TaskManagerServiceReference.RunTasksRequest();
            inValue.UserCredentials = UserCredentials;
            Nephrite.Web.TaskManagerServiceReference.RunTasksResponse retVal = ((Nephrite.Web.TaskManagerServiceReference.TaskManagerService)(this)).RunTasks(inValue);
        }
    }
}
