using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Nephrite.Metamodel.DbSync
{
    internal class View
    {
        internal string Name { get; set; }
        internal string Text { get; set; }
        internal Model Model;

        public View()
        {
        }

        internal void Sync()
        {
            if (Model.Database.Views.Contains(Name))
            {
                var v = Model.Database.Views[Name];
                if (v.TextBody != Text)
                {
                    Model.Log("DROP VIEW " + Name);
                    if (!Model.ScriptOnly)
                        v.Drop();
                }
            }

            var v1 = new Microsoft.SqlServer.Management.Smo.View(Model.Database, Name)
            {
                TextMode = false,
                TextBody = Text
            };

            v1.ExtendedProperties.Add(new Microsoft.SqlServer.Management.Smo.ExtendedProperty(v1, "IsAutoGenerated", 1));

            Model.Log("CREATE VIEW " + Name);
            foreach (var s in v1.Script().OfType<string>())
                Model.Script(s);

            if (!Model.ScriptOnly)
                v1.Create();
        }
    }
}
