<?xml version="1.0" encoding="utf-8"?>
<Database Name="iims" Class="FilterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local);Initial Catalog=Fund2;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.N_Filter" Member="N_Filters">
    <Type Name="N_Filter">
      <Column Name="FilterID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ListName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FilterValue" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FilterName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Group1Column" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Group1Sort" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Group2Column" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Group2Sort" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ListParms" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>